# azure-pipelines.yml
trigger:
- main

pool:
  name: Default

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
- stage: Build
  jobs:
  - job: JobA
    steps:
    - script: |
        echo "##vso[task.setvariable variable=testResult;isOutput=true]passed"
      name: setVar
      displayName: Set output variable

  - job: JobB
    dependsOn: JobA
    variables:
      result: $[ dependencies.JobA.outputs['setVar.testResult'] ]
    condition: eq(dependencies.JobA.outputs['setVar.testResult'], 'passed')
    steps:
    - script: echo "JobB chạy vì testResult = $(result)"
      displayName: Run if passed

  - job: JobC
    dependsOn: JobA
    variables:
      result: $[ dependencies.JobA.outputs['setVar.testResult'] ]
    condition: eq(dependencies.JobA.outputs['setVar.testResult'], 'failed')
    steps:
    - script: echo "JobC chạy vì testResult = failed"
      displayName: Run if failed